version: '3.9'

networks:
  network:
    driver: bridge
    
services:
  db:
    container_name: mariadbwork
    image: mariadb:10.5.9
    restart: always
    ports:
      - '3305:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_PASSWORD=12345678
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --pasword=12345678
      timeout: 10s
      retries: 5
    networks:
      - network

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: 'lw-db-admin'
    ports:
      - '8001:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - network

  laravel:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=db
      - DB_POST=3305
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - DB_DATABASE=laravel
    volumes:
      - './laravel:/app'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
    depends_on:
      - db
    networks:
      - network
  
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - network

volumes:
  db_data:
    driver: local
  db_admin_data:
